### ISSUE TITLE
创建Aot项目Websocket启动报错 “Dynamic code generation is not supported on this platform”

### ISSUE THREAD

**Issue by wobushiafa** [RRQM/TouchSocket#27]
版本：2.0.0-beta.268

[AddSingletonInject(typeof(IPluginManager), typeof(PluginManager))]
[AddSingletonInject(typeof(ILog),typeof(LoggerGroup))]
[AddSingletonInject(typeof(WebSocketFeature))]
[GeneratorContainer]
public partial class CanAotContainer : ManualContainer
{
    
}

    static void Main(string[] args)
    {

        var service = new HttpService();
        service.Setup(new TouchSocketConfig()//加载配置
            .SetListenIPHosts(7789)
            .SetRegistrator(new CanAotContainer())
            .ConfigureContainer(a =>//容器的配置顺序应该在最前面
            {
                a.AddConsoleLogger();//添加一个控制台日志注入（注意：在maui中控制台日志不可用）
                a.RegisterSingleton(service);//将服务器以单例注入。便于插件或其他地方获取。
            })
            .ConfigurePlugins(a =>
            {
                a.UseWebSocket()//添加WebSocket功能
                    .SetWSUrl("/ws")//设置url直接可以连接。
                    .SetVerifyConnection(VerifyConnection)
                    .UseAutoPong();//当收到ping报文时自动回应pong

                a.Add<CloseExceptionPlugin>();
                a.Add<MessageRelayPlugin>();
                a.Add<DisconnectedPlugin>();
            }));

        service.Start();
        service.Logger.Info("服务器已启动");

        Console.ReadKey();
    }

Unhandled exception. System.PlatformNotSupportedException: Dynamic code generation is not supported on this platform.
   at System.Reflection.Emit.AssemblyBuilder.ThrowDynamicCodeNotSupported()
   at System.Reflection.Emit.AssemblyBuilder.EnsureDynamicCodeSupported()
   at System.Reflection.Emit.DynamicMethod.Init(String name, MethodAttributes attributes, CallingConventions callingConvention, Type returnType, Type[] signature, Type owner, Module m, Boolean skipVisibility, Boolean transparentMethod)
   at System.Reflection.Emit.DynamicMethod..ctor(String name, Type returnType, Type[] parameterTypes, Module m)
   at TouchSocket.Core.Method.CreateILInvoker(MethodInfo methodInfo) in D:\CodeOpen\TouchSocketPro\Src\TouchSocket.Core\Reflection\Method.cs:line 363
   at TouchSocket.Core.Method..ctor(MethodInfo method, Boolean build) in D:\CodeOpen\TouchSocketPro\Src\TouchSocket.Core\Reflection\Method.cs:line 83
   at TouchSocket.Core.Method..ctor(MethodInfo method) in D:\CodeOpen\TouchSocketPro\Src\TouchSocket.Core\Reflection\Method.cs:line 59
   at TouchSocket.Core.PluginManager.TouchSocket.Core.IPluginManager.Add(IPlugin plugin) in D:\CodeOpen\TouchSocketPro\Src\TouchSocket.Core\Plugins\PluginManager.cs:line 90
   at TouchSocket.Core.PluginManager.TouchSocket.Core.IPluginManager.Add(Type pluginType) in D:\CodeOpen\TouchSocketPro\Src\TouchSocket.Core\Plugins\PluginManager.cs:line 126
   at TouchSocket.Core.PluginManagerExtension.Add[TPlugin](IPluginManager pluginManager) in D:\CodeOpen\TouchSocketPro\Src\TouchSocket.Core\Plugins\PluginManagerExtension.cs:line 31
   at TouchSocket.Core.WebSocketPluginManagerExtension.UseWebSocket(IPluginManager pluginManager) in D:\CodeOpen\TouchSocketPro\Src\TouchSocket.Http\WebSockets\Extensions\WebSocketPluginsManagerExtension.cs:line 28

**Comment by RRQM** [comment]
感谢您的使用，该bug目前已修复，请更新2.0-beta.273使用

**Comment by wobushiafa** [comment]
> 感谢您的使用，该bug目前已修复，请更新2.0-beta.273使用

真的给力,刚试了一下可以了
